name       : caribou
version    : 0.4.21
release    : 19
source     :
    - https://download.gnome.org/sources/caribou/0.4/caribou-0.4.21.tar.xz : 9c43d9f4bd30f4fea7f780d4e8b14f7589107c52e9cb6bd202bd0d1c2064de55
license    : LGPL-2.1-only
component  : desktop.gnome.core
summary    : A text entry and UI navigation application (on-screen keyboard)
description: |
    A text entry and UI navigation application
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libxklavier)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(xtst)
setup      : |
    PYTHON=python3 %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # caribou is evil and buggy with autostart..
    rm -rf $installdir/etc
